apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-mysql-pvc
spec:
  volumeName: spring-mysql-pv
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi